name: getting-started-actions
on: 
  push:
    branches:
      - node
jobs:
  Build:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out the code to the runner
        uses: actions/checkout@v3
      - name: Set up NodeJs
        uses: actions/setup-node@v3
        with:
          version: '14'
      - name: Install Node Dependences
        run: npm install
        env:
          API_KEY: 123131313131
          PORT: 3000
      - name: Create a new file
        shell: bash
        run: |
          expr 1 + 1 > output.log
      - name: Upload the file
        uses: actions/upload-artifact@v3
        with: 
          name: log-file
          path: output.log
        

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Get files
        uses: actions/download-artifact@v3
        with:
          name: log-file
      - name: Print the result in the files
        shell: bash
        run: |
          value = `cat output.log`
          echo The result is $value


      