name: Testing matrix in actions
on:
  push:
    branches:
      - node
env:
  TOKEN: 12345BITCH
jobs:
  Build:
    runs-on: ubuntu-latest
    env: 
      STEPS: 4
    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJs
        uses: actions/setup-node@v3
        env: 
          NODE_VERSIOM: 14
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Dependencies
        if: ${{ env.STEPS == 2}}
        run: npm install
      - name: Run tests
        run: |
          npm test
          echo "$STEPS - $TOKEN"
        
